### ISSUE TITLE
Install with juliaup?

### ISSUE THREAD

**Issue by sjkelly** [julia-vscode/julia-devcontainer#19]
This container is really helpful to get up and running with codespaces quite easily. However, often times I am interested in testing on several Julia versions in the container. I am wondering if it makes sense to use juliaup to manager the installs, making it easy for a user to add a new Julia version once they are in the devcontainer.

**Comment by eitsupi** [comment]
@sjkelly Use the Dev Container Feature instead of this repo.
https://github.com/JuliaLang/devcontainer-features

**Comment by gerlero** [comment]
> @sjkelly Use the Dev Container Feature instead of this repo.
> https://github.com/JuliaLang/devcontainer-features

@eitsupi thanks for the work on these projects. I see a substantial overlap between the target use cases and developers of that project and this one. Do you have a recommendation on whether some generic Julia project should prefer using this container image vs. a standard devcontainer with that feature added to it?

**Comment by eitsupi** [comment]
@gerlero I believe that this repository is outdated and that there is essentially no advantage to continuing to use.
See https://github.com/microsoft/vscode-dev-containers/issues/1114#issuecomment-1370183255.

Since Julia is very lightweight and can be installed in seconds, it is very easy to install any Julia using the julia Feature on a base image of your choice.

However, for now the Julia Feature lacks postCreateCommand (JuliaLang/devcontainer-features#9).
If you would like to use this, a PR to add this would be an excellent contribution.
